### ISSUE TITLE
fela-bindings 10.6.0 expects a document, breaks server rendering

### ISSUE THREAD

**Issue by bensmithett** [robinweser/fela#727]
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela-bindings     | 10.6.0   |
| react-fela     | 10.6.0   |

-------------------
#### Description

A change to `RendererProviderFactory` in 10.6.0 added `document` as a default parameter to a couple of functions, including `hasDOM`: https://github.com/robinweser/fela/commit/b956c3e83591cef4458f3e4074c4e0267a5d69e8#diff-a616f11ba186e1fe3ce315bad2e11662

When using `RendererProvider` from `react-fela@10.6.0`, this causes server rendering to error because `document` doesn't exist.

[Previously](https://github.com/robinweser/fela/commit/b956c3e83591cef4458f3e4074c4e0267a5d69e8#diff-a616f11ba186e1fe3ce315bad2e11662R9) you were checking for `typeof window !== 'undefined'` before accessing `document`.

#### Steps to reproduce

Minimal reproducible example here: https://github.com/bensmithett/fela-issue-test-case/blob/master/test.js

#### Expected Output

```bash
html
<div class="a"></div>
------------------------------
css
<style type="text/css" data-fela-rehydration="1" data-fela-type="RULE">.a{color:blue}</style>
```

#### Actual Output

```bash
~/fela-issue-test-case/node_modules/react-dom/cjs/react-dom-server.node.development.js:3166
            throw err;
            ^

ReferenceError: document is not defined
    at hasDOM (~/fela-issue-test-case/node_modules/fela-bindings/lib/RendererProviderFactory.js:26:92)
    at RendererProvider._renderStyle (~/fela-issue-test-case/node_modules/fela-bindings/lib/RendererProviderFactory.js:65:13)
    at new RendererProvider (~/fela-issue-test-case/node_modules/fela-bindings/lib/RendererProviderFactory.js:46:13)
    at processChild (~/fela-issue-test-case/node_modules/react-dom/cjs/react-dom-server.node.development.js:2846:14)
    at resolve (~/fela-issue-test-case/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (~/fela-issue-test-case/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (~/fela-issue-test-case/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at Object.renderToString (~/fela-issue-test-case/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at Object.<anonymous> (~/fela-issue-test-case/test.js:26:28)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
```

**Comment by robinweser** [comment]
Oh, I must have deleted it unintentionally. Would you want to send a PR to fix it? I'll merge asap!

**Comment by bensmithett** [comment]
@robinweser yep! Incoming shortly...

**Comment by MrOggy85** [comment]
This still breaks in react-native. 
`window` exists
but `document` is not defined which results in an error:
> `document is not defined`
